# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.DateTimeField(verbose_name='Date Played')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('player_rank', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loser', to='Ladder.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='Ladder.Player'),
        ),
    ]
