# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ladder', '0002_auto_20170213_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_loser_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='game_winner_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_rank',
            field=models.IntegerField(default=0),
        ),
    ]
